spring:
    application:
        name: BootJPA26-UsingMySQL-PL-SQL-Procedure-Calling
    datasource:
        username: root
        password: root
        url: jdbc:mysql:///datajpa
        driver-class-name: com.mysql.cj.jdbc.Driver
        # JPA- hibernate properties
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                enable_lazy_load_no_trans:true
    # enable hibernate lazy loading with out transaction mgmt  (required for getOne(-),getById(-) and getByReference(-) methods)