spring:
    application:
        name: BootJPA28-Versioning-TimeStampping
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/orcl
        username: system
        password: raj
    jpa:
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update
        show-sql: true