spring:
    application:
        name: BootJPA13-DeleteEntityOneRecords
    datasource:
        username: system
        password: raj
        url: jdbc:oracle:thin:@localhost:1521:orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
    jpa:
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update
        show-sql: true