spring:
    application:
        name: BootJPA07-FindAllMethodInFinderMethod
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: system
        password: raj
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update