mysql:
    ds:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql:///rajyadavdb
        password: root
        username: root
ora:
    ds:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        jdbc-url: jdbc:oracle:thin:@localhost:1521/orcl
        password: raj
        username: system
spring:
    application:
        name: BootJPA33-InteractingWithTwoDatabases
