spring:
    application:
        name: BootMail-SpringBootMail-SendAttachmentOperation
    mail:
        host: smtp.gmail.com
        port: 587
        username: your_email_id_here
        password: your_app_password_here
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 100000
                    writetimeout: 100000
                    timeout: 30000