spring:
    application:
        name: BootJPA15-DeleteMultipleUsingListOfIds
    datasource:
        username: system
        password: raj
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/orcl
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update