spring:
    application:
        name: BootJPA04-ExistByID
# Data Source Configuration
    datasource:
        username: system
        password: raj
        url: jdbc:oracle:thin:@localhost:1521:orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
        hikari:
            minimum-idle: 10
            keepalive-time: 1000000
#JPA Configuration
    jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.OracleDialect
        show-sql: true